name: EdgarDear
favicon: null
layout_spectrum: 0.90371
typography_spectrum: 0.7969947732053697
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.174399689771235
  lightness: 0.5515350848436356
  saturation: 0.9397642374970019
  rhythmicContrast: 0.6313741572666913
purpose: []
